title: scratch-coolest-projects
hero_image: images/banner.png
description: scratch-coolest-projects description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
