---
title: Coolest Projectsに参加しよう
hero_image: images/banner.png
description: 世界をリードする若者向けのテクノロジーショーケースであるCoolest Projectsに参加しよう
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Coolest Projectsに参加しよう
