---
title: Werde Teil von "Coolest Projects"
hero_image: images/banner.png
description: Du kann an Coolest Projects teilnehmen, der weltweit größten Technologie-Präsentation für junge Menschen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Werde Teil von "Coolest Projects"
