---
title: Participe do Coolest Projects
hero_image: images/banner.png
description: Participe do Coolest Projects, a principal exposição mundial de tecnologia para jovens.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Participe do Coolest Projects
