---
title: Zúčastněte se projektu Coolest Projects
hero_image: images/banner.png
description: Zúčastněte se Coolest Projects, přední světové technologické prezentace pro mladé lidi
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - title: Zúčastněte se projektu Coolest Projects
