---
title: Participa en Coolest Projects
hero_image: images/banner.png
description: Participa en Coolest Projects, la exhibición de tecnología líder en el mundo para los jóvenes
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Participa en Coolest Projects
