---
title: Weź udział w Coolest Projects
hero_image: images/banner.png
description: Weź udział w Coolest Projects, wiodącej na świecie prezentacji technologicznej dla młodych ludzi
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Weź udział w Coolest Projects
