---
title: Delta i Coolest Projects
hero_image: images/banner.png
description: Delta i Coolest Projects, världens ledande teknikutställning för unga
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Delta i Coolest Projects
