---
title: Λάβετε μέρος σε πιο cool έργα
hero_image: images/banner.png
description: Πάρτε μέρος στα Coolest Projects, την κορυφαία έκθεση τεχνολογίας στον κόσμο για νέους
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Λάβετε μέρος σε πιο cool έργα
