---
title: Participer à Coolest Projects
hero_image: images/banner.png
description: Take part in Coolest Projects, the world’s leading technology showcase for young people
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Participer à Coolest Projects
