---
title: Participer à Coolest Projects
hero_image: images/banner.png
description: Participer à Coolest Projects, la principale vitrine technologique au monde pour les jeunes.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-11"
steps:
  - 
    title: Participer à Coolest Projects
